# stub for old docker that fails the build if unused argument is passed
ARG SELENIUM_VERSION
ARG CHROME_DRIVER_VERSION
ARG CHROME_SHA512
ARG CHROME_VERSION

USER seluser

#====================================
# Scripts to run Selenium Standalone
#====================================
COPY start-selenium-standalone.sh /opt/bin/start-selenium-standalone.sh

#==============================
# Supervisor configuration file
#==============================
COPY selenium.conf /etc/supervisor/conf.d/


EXPOSE 4444
